# Generated by Django 4.0.4 on 2022-04-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_alter_notes_title_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'HomeWork', 'verbose_name_plural': 'HomeWork'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
